/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForCouplesAndFamiliesRouteImport } from './routes/for-couples-and-families'
import { Route as ForFreelancersRouteImport } from './routes/for-freelancers'
import { Route as OgRouteImport } from './routes/og'
import { Route as OpenSourceRouteImport } from './routes/open-source'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as VsSpreadsheetsRouteImport } from './routes/vs-spreadsheets'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as FeaturesAiAnalystRouteImport } from './routes/features/ai-analyst'
import { Route as FeaturesBankConnectionsRouteImport } from './routes/features/bank-connections'
import { Route as FeaturesCashFlowRouteImport } from './routes/features/cash-flow'
import { Route as FeaturesReportsRouteImport } from './routes/features/reports'
import { Route as FeaturesZeroBasedPlanRouteImport } from './routes/features/zero-based-plan'
import { Route as GuidesCancelUnusedSubscriptionsRouteImport } from './routes/guides/cancel-unused-subscriptions'
import { Route as GuidesCashFlowForecastRouteImport } from './routes/guides/cash-flow-forecast'
import { Route as GuidesZeroBasedBudgetingRouteImport } from './routes/guides/zero-based-budgeting'
import { Route as ItIndexRouteImport } from './routes/it/index'
import { Route as ItDomandeFrequentiRouteImport } from './routes/it/domande-frequenti'
import { Route as ItOpenSourceRouteImport } from './routes/it/open-source'
import { Route as ItPerCoppieEFamiglieRouteImport } from './routes/it/per-coppie-e-famiglie'
import { Route as ItPerFreelanceEPartitaIvaRouteImport } from './routes/it/per-freelance-e-partita-iva'
import { Route as ItPrezziRouteImport } from './routes/it/prezzi'
import { Route as ItVsFogliDiCalcoloRouteImport } from './routes/it/vs-fogli-di-calcolo'
import { Route as ItFunzioniAnalystAiRouteImport } from './routes/it/funzioni/analyst-ai'
import { Route as ItFunzioniCollegamentoBancarioRouteImport } from './routes/it/funzioni/collegamento-bancario'
import { Route as ItFunzioniFlussoDiCassaRouteImport } from './routes/it/funzioni/flusso-di-cassa'
import { Route as ItFunzioniPianoZeroBasedRouteImport } from './routes/it/funzioni/piano-zero-based'
import { Route as ItFunzioniReportRouteImport } from './routes/it/funzioni/report'
import { Route as ItGuideBudgetZeroBasedRouteImport } from './routes/it/guide/budget-zero-based'
import { Route as ItGuideCancellaAbbonamentiInutiliRouteImport } from './routes/it/guide/cancella-abbonamenti-inutili'
import { Route as ItGuidePrevisioneFlussoDiCassaRouteImport } from './routes/it/guide/previsione-flusso-di-cassa'
import { Route as AuthenticatedAppAppIndexRouteImport } from './routes/_authenticated/_app/app/index'
import { Route as AuthenticatedAppAppAnalystRouteImport } from './routes/_authenticated/_app/app/analyst'
import { Route as AuthenticatedAppAppDocsRouteImport } from './routes/_authenticated/_app/app/docs'
import { Route as AuthenticatedAppAppForecastRouteImport } from './routes/_authenticated/_app/app/forecast'
import { Route as AuthenticatedAppAppGoalsRouteImport } from './routes/_authenticated/_app/app/goals'
import { Route as AuthenticatedAppAppImportRouteImport } from './routes/_authenticated/_app/app/import'
import { Route as AuthenticatedAppAppPlanRouteImport } from './routes/_authenticated/_app/app/plan'
import { Route as AuthenticatedAppAppPlanningRouteImport } from './routes/_authenticated/_app/app/planning'
import { Route as AuthenticatedAppAppReportsRouteImport } from './routes/_authenticated/_app/app/reports'
import { Route as AuthenticatedAppAppSettingsRouteImport } from './routes/_authenticated/_app/app/settings'
import { Route as AuthenticatedAppAppTransactionsRouteImport } from './routes/_authenticated/_app/app/transactions'
import { Route as AuthenticatedAppAppAccountsIndexRouteImport } from './routes/_authenticated/_app/app/accounts/index'
import { Route as AuthenticatedAppAppAccountsAccountIdRouteImport } from './routes/_authenticated/_app/app/accounts/$accountId'
import { Route as AuthenticatedAppAppDocsIndexRouteImport } from './routes/_authenticated/_app/app/docs/index'
import { Route as AuthenticatedAppAppDocsSlugRouteImport } from './routes/_authenticated/_app/app/docs/$slug'
import { Route as AuthenticatedAppAppLoansFacilityIdRouteImport } from './routes/_authenticated/_app/app/loans/$facilityId'
import { Route as AuthenticatedAppAppSettingsIndexRouteImport } from './routes/_authenticated/_app/app/settings/index'
import { Route as AuthenticatedAppAppSettingsAccountsRouteImport } from './routes/_authenticated/_app/app/settings/accounts'
import { Route as AuthenticatedAppAppSettingsBankConnectionsRouteImport } from './routes/_authenticated/_app/app/settings/bank-connections'
import { Route as AuthenticatedAppAppSettingsCreditRouteImport } from './routes/_authenticated/_app/app/settings/credit'
import { Route as AuthenticatedAppAppSettingsDeletingRouteImport } from './routes/_authenticated/_app/app/settings/deleting'
import { Route as AuthenticatedAppAppSettingsImportRouteImport } from './routes/_authenticated/_app/app/settings/import'
import { Route as AuthenticatedAppAppSubscriptionsIndexRouteImport } from './routes/_authenticated/_app/app/subscriptions/index'
import { Route as AuthenticatedAppAppSubscriptionsCreateRouteImport } from './routes/_authenticated/_app/app/subscriptions/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCouplesAndFamiliesRoute = ForCouplesAndFamiliesRouteImport.update({
  id: '/for-couples-and-families',
  path: '/for-couples-and-families',
  getParentRoute: () => rootRouteImport,
} as any)
const ForFreelancersRoute = ForFreelancersRouteImport.update({
  id: '/for-freelancers',
  path: '/for-freelancers',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceRoute = OpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const VsSpreadsheetsRoute = VsSpreadsheetsRouteImport.update({
  id: '/vs-spreadsheets',
  path: '/vs-spreadsheets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const FeaturesAiAnalystRoute = FeaturesAiAnalystRouteImport.update({
  id: '/features/ai-analyst',
  path: '/features/ai-analyst',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesBankConnectionsRoute = FeaturesBankConnectionsRouteImport.update({
  id: '/features/bank-connections',
  path: '/features/bank-connections',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesCashFlowRoute = FeaturesCashFlowRouteImport.update({
  id: '/features/cash-flow',
  path: '/features/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesReportsRoute = FeaturesReportsRouteImport.update({
  id: '/features/reports',
  path: '/features/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesZeroBasedPlanRoute = FeaturesZeroBasedPlanRouteImport.update({
  id: '/features/zero-based-plan',
  path: '/features/zero-based-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesCancelUnusedSubscriptionsRoute =
  GuidesCancelUnusedSubscriptionsRouteImport.update({
    id: '/guides/cancel-unused-subscriptions',
    path: '/guides/cancel-unused-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesCashFlowForecastRoute = GuidesCashFlowForecastRouteImport.update({
  id: '/guides/cash-flow-forecast',
  path: '/guides/cash-flow-forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesZeroBasedBudgetingRoute =
  GuidesZeroBasedBudgetingRouteImport.update({
    id: '/guides/zero-based-budgeting',
    path: '/guides/zero-based-budgeting',
    getParentRoute: () => rootRouteImport,
  } as any)
const ItIndexRoute = ItIndexRouteImport.update({
  id: '/it/',
  path: '/it/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItDomandeFrequentiRoute = ItDomandeFrequentiRouteImport.update({
  id: '/it/domande-frequenti',
  path: '/it/domande-frequenti',
  getParentRoute: () => rootRouteImport,
} as any)
const ItOpenSourceRoute = ItOpenSourceRouteImport.update({
  id: '/it/open-source',
  path: '/it/open-source',
  getParentRoute: () => rootRouteImport,
} as any)
const ItPerCoppieEFamiglieRoute = ItPerCoppieEFamiglieRouteImport.update({
  id: '/it/per-coppie-e-famiglie',
  path: '/it/per-coppie-e-famiglie',
  getParentRoute: () => rootRouteImport,
} as any)
const ItPerFreelanceEPartitaIvaRoute =
  ItPerFreelanceEPartitaIvaRouteImport.update({
    id: '/it/per-freelance-e-partita-iva',
    path: '/it/per-freelance-e-partita-iva',
    getParentRoute: () => rootRouteImport,
  } as any)
const ItPrezziRoute = ItPrezziRouteImport.update({
  id: '/it/prezzi',
  path: '/it/prezzi',
  getParentRoute: () => rootRouteImport,
} as any)
const ItVsFogliDiCalcoloRoute = ItVsFogliDiCalcoloRouteImport.update({
  id: '/it/vs-fogli-di-calcolo',
  path: '/it/vs-fogli-di-calcolo',
  getParentRoute: () => rootRouteImport,
} as any)
const ItFunzioniAnalystAiRoute = ItFunzioniAnalystAiRouteImport.update({
  id: '/it/funzioni/analyst-ai',
  path: '/it/funzioni/analyst-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ItFunzioniCollegamentoBancarioRoute =
  ItFunzioniCollegamentoBancarioRouteImport.update({
    id: '/it/funzioni/collegamento-bancario',
    path: '/it/funzioni/collegamento-bancario',
    getParentRoute: () => rootRouteImport,
  } as any)
const ItFunzioniFlussoDiCassaRoute = ItFunzioniFlussoDiCassaRouteImport.update({
  id: '/it/funzioni/flusso-di-cassa',
  path: '/it/funzioni/flusso-di-cassa',
  getParentRoute: () => rootRouteImport,
} as any)
const ItFunzioniPianoZeroBasedRoute =
  ItFunzioniPianoZeroBasedRouteImport.update({
    id: '/it/funzioni/piano-zero-based',
    path: '/it/funzioni/piano-zero-based',
    getParentRoute: () => rootRouteImport,
  } as any)
const ItFunzioniReportRoute = ItFunzioniReportRouteImport.update({
  id: '/it/funzioni/report',
  path: '/it/funzioni/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ItGuideBudgetZeroBasedRoute = ItGuideBudgetZeroBasedRouteImport.update({
  id: '/it/guide/budget-zero-based',
  path: '/it/guide/budget-zero-based',
  getParentRoute: () => rootRouteImport,
} as any)
const ItGuideCancellaAbbonamentiInutiliRoute =
  ItGuideCancellaAbbonamentiInutiliRouteImport.update({
    id: '/it/guide/cancella-abbonamenti-inutili',
    path: '/it/guide/cancella-abbonamenti-inutili',
    getParentRoute: () => rootRouteImport,
  } as any)
const ItGuidePrevisioneFlussoDiCassaRoute =
  ItGuidePrevisioneFlussoDiCassaRouteImport.update({
    id: '/it/guide/previsione-flusso-di-cassa',
    path: '/it/guide/previsione-flusso-di-cassa',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppAppIndexRoute =
  AuthenticatedAppAppIndexRouteImport.update({
    id: '/app/',
    path: '/app/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppAnalystRoute =
  AuthenticatedAppAppAnalystRouteImport.update({
    id: '/app/analyst',
    path: '/app/analyst',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppDocsRoute = AuthenticatedAppAppDocsRouteImport.update({
  id: '/app/docs',
  path: '/app/docs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAppForecastRoute =
  AuthenticatedAppAppForecastRouteImport.update({
    id: '/app/forecast',
    path: '/app/forecast',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppGoalsRoute =
  AuthenticatedAppAppGoalsRouteImport.update({
    id: '/app/goals',
    path: '/app/goals',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppImportRoute =
  AuthenticatedAppAppImportRouteImport.update({
    id: '/app/import',
    path: '/app/import',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppPlanRoute = AuthenticatedAppAppPlanRouteImport.update({
  id: '/app/plan',
  path: '/app/plan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAppPlanningRoute =
  AuthenticatedAppAppPlanningRouteImport.update({
    id: '/app/planning',
    path: '/app/planning',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppReportsRoute =
  AuthenticatedAppAppReportsRouteImport.update({
    id: '/app/reports',
    path: '/app/reports',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppSettingsRoute =
  AuthenticatedAppAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppTransactionsRoute =
  AuthenticatedAppAppTransactionsRouteImport.update({
    id: '/app/transactions',
    path: '/app/transactions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppAccountsIndexRoute =
  AuthenticatedAppAppAccountsIndexRouteImport.update({
    id: '/app/accounts/',
    path: '/app/accounts/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppAccountsAccountIdRoute =
  AuthenticatedAppAppAccountsAccountIdRouteImport.update({
    id: '/app/accounts/$accountId',
    path: '/app/accounts/$accountId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppDocsIndexRoute =
  AuthenticatedAppAppDocsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAppDocsRoute,
  } as any)
const AuthenticatedAppAppDocsSlugRoute =
  AuthenticatedAppAppDocsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAppAppDocsRoute,
  } as any)
const AuthenticatedAppAppLoansFacilityIdRoute =
  AuthenticatedAppAppLoansFacilityIdRouteImport.update({
    id: '/app/loans/$facilityId',
    path: '/app/loans/$facilityId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppSettingsIndexRoute =
  AuthenticatedAppAppSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAppSettingsRoute,
  } as any)
const AuthenticatedAppAppSettingsAccountsRoute =
  AuthenticatedAppAppSettingsAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAppAppSettingsRoute,
  } as any)
const AuthenticatedAppAppSettingsBankConnectionsRoute =
  AuthenticatedAppAppSettingsBankConnectionsRouteImport.update({
    id: '/bank-connections',
    path: '/bank-connections',
    getParentRoute: () => AuthenticatedAppAppSettingsRoute,
  } as any)
const AuthenticatedAppAppSettingsCreditRoute =
  AuthenticatedAppAppSettingsCreditRouteImport.update({
    id: '/credit',
    path: '/credit',
    getParentRoute: () => AuthenticatedAppAppSettingsRoute,
  } as any)
const AuthenticatedAppAppSettingsDeletingRoute =
  AuthenticatedAppAppSettingsDeletingRouteImport.update({
    id: '/deleting',
    path: '/deleting',
    getParentRoute: () => AuthenticatedAppAppSettingsRoute,
  } as any)
const AuthenticatedAppAppSettingsImportRoute =
  AuthenticatedAppAppSettingsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAppAppSettingsRoute,
  } as any)
const AuthenticatedAppAppSubscriptionsIndexRoute =
  AuthenticatedAppAppSubscriptionsIndexRouteImport.update({
    id: '/app/subscriptions/',
    path: '/app/subscriptions/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppSubscriptionsCreateRoute =
  AuthenticatedAppAppSubscriptionsCreateRouteImport.update({
    id: '/app/subscriptions/create',
    path: '/app/subscriptions/create',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/faq': typeof FaqRoute
  '/for-couples-and-families': typeof ForCouplesAndFamiliesRoute
  '/for-freelancers': typeof ForFreelancersRoute
  '/og': typeof OgRoute
  '/open-source': typeof OpenSourceRoute
  '/pricing': typeof PricingRoute
  '/vs-spreadsheets': typeof VsSpreadsheetsRoute
  '/features/ai-analyst': typeof FeaturesAiAnalystRoute
  '/features/bank-connections': typeof FeaturesBankConnectionsRoute
  '/features/cash-flow': typeof FeaturesCashFlowRoute
  '/features/reports': typeof FeaturesReportsRoute
  '/features/zero-based-plan': typeof FeaturesZeroBasedPlanRoute
  '/guides/cancel-unused-subscriptions': typeof GuidesCancelUnusedSubscriptionsRoute
  '/guides/cash-flow-forecast': typeof GuidesCashFlowForecastRoute
  '/guides/zero-based-budgeting': typeof GuidesZeroBasedBudgetingRoute
  '/it/domande-frequenti': typeof ItDomandeFrequentiRoute
  '/it/open-source': typeof ItOpenSourceRoute
  '/it/per-coppie-e-famiglie': typeof ItPerCoppieEFamiglieRoute
  '/it/per-freelance-e-partita-iva': typeof ItPerFreelanceEPartitaIvaRoute
  '/it/prezzi': typeof ItPrezziRoute
  '/it/vs-fogli-di-calcolo': typeof ItVsFogliDiCalcoloRoute
  '/it/': typeof ItIndexRoute
  '/it/funzioni/analyst-ai': typeof ItFunzioniAnalystAiRoute
  '/it/funzioni/collegamento-bancario': typeof ItFunzioniCollegamentoBancarioRoute
  '/it/funzioni/flusso-di-cassa': typeof ItFunzioniFlussoDiCassaRoute
  '/it/funzioni/piano-zero-based': typeof ItFunzioniPianoZeroBasedRoute
  '/it/funzioni/report': typeof ItFunzioniReportRoute
  '/it/guide/budget-zero-based': typeof ItGuideBudgetZeroBasedRoute
  '/it/guide/cancella-abbonamenti-inutili': typeof ItGuideCancellaAbbonamentiInutiliRoute
  '/it/guide/previsione-flusso-di-cassa': typeof ItGuidePrevisioneFlussoDiCassaRoute
  '/app/analyst': typeof AuthenticatedAppAppAnalystRoute
  '/app/docs': typeof AuthenticatedAppAppDocsRouteWithChildren
  '/app/forecast': typeof AuthenticatedAppAppForecastRoute
  '/app/goals': typeof AuthenticatedAppAppGoalsRoute
  '/app/import': typeof AuthenticatedAppAppImportRoute
  '/app/plan': typeof AuthenticatedAppAppPlanRoute
  '/app/planning': typeof AuthenticatedAppAppPlanningRoute
  '/app/reports': typeof AuthenticatedAppAppReportsRoute
  '/app/settings': typeof AuthenticatedAppAppSettingsRouteWithChildren
  '/app/transactions': typeof AuthenticatedAppAppTransactionsRoute
  '/app/': typeof AuthenticatedAppAppIndexRoute
  '/app/accounts/$accountId': typeof AuthenticatedAppAppAccountsAccountIdRoute
  '/app/docs/$slug': typeof AuthenticatedAppAppDocsSlugRoute
  '/app/loans/$facilityId': typeof AuthenticatedAppAppLoansFacilityIdRoute
  '/app/settings/accounts': typeof AuthenticatedAppAppSettingsAccountsRoute
  '/app/settings/bank-connections': typeof AuthenticatedAppAppSettingsBankConnectionsRoute
  '/app/settings/credit': typeof AuthenticatedAppAppSettingsCreditRoute
  '/app/settings/deleting': typeof AuthenticatedAppAppSettingsDeletingRoute
  '/app/settings/import': typeof AuthenticatedAppAppSettingsImportRoute
  '/app/subscriptions/create': typeof AuthenticatedAppAppSubscriptionsCreateRoute
  '/app/accounts/': typeof AuthenticatedAppAppAccountsIndexRoute
  '/app/docs/': typeof AuthenticatedAppAppDocsIndexRoute
  '/app/settings/': typeof AuthenticatedAppAppSettingsIndexRoute
  '/app/subscriptions/': typeof AuthenticatedAppAppSubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/faq': typeof FaqRoute
  '/for-couples-and-families': typeof ForCouplesAndFamiliesRoute
  '/for-freelancers': typeof ForFreelancersRoute
  '/og': typeof OgRoute
  '/open-source': typeof OpenSourceRoute
  '/pricing': typeof PricingRoute
  '/vs-spreadsheets': typeof VsSpreadsheetsRoute
  '/features/ai-analyst': typeof FeaturesAiAnalystRoute
  '/features/bank-connections': typeof FeaturesBankConnectionsRoute
  '/features/cash-flow': typeof FeaturesCashFlowRoute
  '/features/reports': typeof FeaturesReportsRoute
  '/features/zero-based-plan': typeof FeaturesZeroBasedPlanRoute
  '/guides/cancel-unused-subscriptions': typeof GuidesCancelUnusedSubscriptionsRoute
  '/guides/cash-flow-forecast': typeof GuidesCashFlowForecastRoute
  '/guides/zero-based-budgeting': typeof GuidesZeroBasedBudgetingRoute
  '/it/domande-frequenti': typeof ItDomandeFrequentiRoute
  '/it/open-source': typeof ItOpenSourceRoute
  '/it/per-coppie-e-famiglie': typeof ItPerCoppieEFamiglieRoute
  '/it/per-freelance-e-partita-iva': typeof ItPerFreelanceEPartitaIvaRoute
  '/it/prezzi': typeof ItPrezziRoute
  '/it/vs-fogli-di-calcolo': typeof ItVsFogliDiCalcoloRoute
  '/it': typeof ItIndexRoute
  '/it/funzioni/analyst-ai': typeof ItFunzioniAnalystAiRoute
  '/it/funzioni/collegamento-bancario': typeof ItFunzioniCollegamentoBancarioRoute
  '/it/funzioni/flusso-di-cassa': typeof ItFunzioniFlussoDiCassaRoute
  '/it/funzioni/piano-zero-based': typeof ItFunzioniPianoZeroBasedRoute
  '/it/funzioni/report': typeof ItFunzioniReportRoute
  '/it/guide/budget-zero-based': typeof ItGuideBudgetZeroBasedRoute
  '/it/guide/cancella-abbonamenti-inutili': typeof ItGuideCancellaAbbonamentiInutiliRoute
  '/it/guide/previsione-flusso-di-cassa': typeof ItGuidePrevisioneFlussoDiCassaRoute
  '/app/analyst': typeof AuthenticatedAppAppAnalystRoute
  '/app/forecast': typeof AuthenticatedAppAppForecastRoute
  '/app/goals': typeof AuthenticatedAppAppGoalsRoute
  '/app/import': typeof AuthenticatedAppAppImportRoute
  '/app/plan': typeof AuthenticatedAppAppPlanRoute
  '/app/planning': typeof AuthenticatedAppAppPlanningRoute
  '/app/reports': typeof AuthenticatedAppAppReportsRoute
  '/app/transactions': typeof AuthenticatedAppAppTransactionsRoute
  '/app': typeof AuthenticatedAppAppIndexRoute
  '/app/accounts/$accountId': typeof AuthenticatedAppAppAccountsAccountIdRoute
  '/app/docs/$slug': typeof AuthenticatedAppAppDocsSlugRoute
  '/app/loans/$facilityId': typeof AuthenticatedAppAppLoansFacilityIdRoute
  '/app/settings/accounts': typeof AuthenticatedAppAppSettingsAccountsRoute
  '/app/settings/bank-connections': typeof AuthenticatedAppAppSettingsBankConnectionsRoute
  '/app/settings/credit': typeof AuthenticatedAppAppSettingsCreditRoute
  '/app/settings/deleting': typeof AuthenticatedAppAppSettingsDeletingRoute
  '/app/settings/import': typeof AuthenticatedAppAppSettingsImportRoute
  '/app/subscriptions/create': typeof AuthenticatedAppAppSubscriptionsCreateRoute
  '/app/accounts': typeof AuthenticatedAppAppAccountsIndexRoute
  '/app/docs': typeof AuthenticatedAppAppDocsIndexRoute
  '/app/settings': typeof AuthenticatedAppAppSettingsIndexRoute
  '/app/subscriptions': typeof AuthenticatedAppAppSubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/faq': typeof FaqRoute
  '/for-couples-and-families': typeof ForCouplesAndFamiliesRoute
  '/for-freelancers': typeof ForFreelancersRoute
  '/og': typeof OgRoute
  '/open-source': typeof OpenSourceRoute
  '/pricing': typeof PricingRoute
  '/vs-spreadsheets': typeof VsSpreadsheetsRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/features/ai-analyst': typeof FeaturesAiAnalystRoute
  '/features/bank-connections': typeof FeaturesBankConnectionsRoute
  '/features/cash-flow': typeof FeaturesCashFlowRoute
  '/features/reports': typeof FeaturesReportsRoute
  '/features/zero-based-plan': typeof FeaturesZeroBasedPlanRoute
  '/guides/cancel-unused-subscriptions': typeof GuidesCancelUnusedSubscriptionsRoute
  '/guides/cash-flow-forecast': typeof GuidesCashFlowForecastRoute
  '/guides/zero-based-budgeting': typeof GuidesZeroBasedBudgetingRoute
  '/it/domande-frequenti': typeof ItDomandeFrequentiRoute
  '/it/open-source': typeof ItOpenSourceRoute
  '/it/per-coppie-e-famiglie': typeof ItPerCoppieEFamiglieRoute
  '/it/per-freelance-e-partita-iva': typeof ItPerFreelanceEPartitaIvaRoute
  '/it/prezzi': typeof ItPrezziRoute
  '/it/vs-fogli-di-calcolo': typeof ItVsFogliDiCalcoloRoute
  '/it/': typeof ItIndexRoute
  '/it/funzioni/analyst-ai': typeof ItFunzioniAnalystAiRoute
  '/it/funzioni/collegamento-bancario': typeof ItFunzioniCollegamentoBancarioRoute
  '/it/funzioni/flusso-di-cassa': typeof ItFunzioniFlussoDiCassaRoute
  '/it/funzioni/piano-zero-based': typeof ItFunzioniPianoZeroBasedRoute
  '/it/funzioni/report': typeof ItFunzioniReportRoute
  '/it/guide/budget-zero-based': typeof ItGuideBudgetZeroBasedRoute
  '/it/guide/cancella-abbonamenti-inutili': typeof ItGuideCancellaAbbonamentiInutiliRoute
  '/it/guide/previsione-flusso-di-cassa': typeof ItGuidePrevisioneFlussoDiCassaRoute
  '/_authenticated/_app/app/analyst': typeof AuthenticatedAppAppAnalystRoute
  '/_authenticated/_app/app/docs': typeof AuthenticatedAppAppDocsRouteWithChildren
  '/_authenticated/_app/app/forecast': typeof AuthenticatedAppAppForecastRoute
  '/_authenticated/_app/app/goals': typeof AuthenticatedAppAppGoalsRoute
  '/_authenticated/_app/app/import': typeof AuthenticatedAppAppImportRoute
  '/_authenticated/_app/app/plan': typeof AuthenticatedAppAppPlanRoute
  '/_authenticated/_app/app/planning': typeof AuthenticatedAppAppPlanningRoute
  '/_authenticated/_app/app/reports': typeof AuthenticatedAppAppReportsRoute
  '/_authenticated/_app/app/settings': typeof AuthenticatedAppAppSettingsRouteWithChildren
  '/_authenticated/_app/app/transactions': typeof AuthenticatedAppAppTransactionsRoute
  '/_authenticated/_app/app/': typeof AuthenticatedAppAppIndexRoute
  '/_authenticated/_app/app/accounts/$accountId': typeof AuthenticatedAppAppAccountsAccountIdRoute
  '/_authenticated/_app/app/docs/$slug': typeof AuthenticatedAppAppDocsSlugRoute
  '/_authenticated/_app/app/loans/$facilityId': typeof AuthenticatedAppAppLoansFacilityIdRoute
  '/_authenticated/_app/app/settings/accounts': typeof AuthenticatedAppAppSettingsAccountsRoute
  '/_authenticated/_app/app/settings/bank-connections': typeof AuthenticatedAppAppSettingsBankConnectionsRoute
  '/_authenticated/_app/app/settings/credit': typeof AuthenticatedAppAppSettingsCreditRoute
  '/_authenticated/_app/app/settings/deleting': typeof AuthenticatedAppAppSettingsDeletingRoute
  '/_authenticated/_app/app/settings/import': typeof AuthenticatedAppAppSettingsImportRoute
  '/_authenticated/_app/app/subscriptions/create': typeof AuthenticatedAppAppSubscriptionsCreateRoute
  '/_authenticated/_app/app/accounts/': typeof AuthenticatedAppAppAccountsIndexRoute
  '/_authenticated/_app/app/docs/': typeof AuthenticatedAppAppDocsIndexRoute
  '/_authenticated/_app/app/settings/': typeof AuthenticatedAppAppSettingsIndexRoute
  '/_authenticated/_app/app/subscriptions/': typeof AuthenticatedAppAppSubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/faq'
    | '/for-couples-and-families'
    | '/for-freelancers'
    | '/og'
    | '/open-source'
    | '/pricing'
    | '/vs-spreadsheets'
    | '/features/ai-analyst'
    | '/features/bank-connections'
    | '/features/cash-flow'
    | '/features/reports'
    | '/features/zero-based-plan'
    | '/guides/cancel-unused-subscriptions'
    | '/guides/cash-flow-forecast'
    | '/guides/zero-based-budgeting'
    | '/it/domande-frequenti'
    | '/it/open-source'
    | '/it/per-coppie-e-famiglie'
    | '/it/per-freelance-e-partita-iva'
    | '/it/prezzi'
    | '/it/vs-fogli-di-calcolo'
    | '/it/'
    | '/it/funzioni/analyst-ai'
    | '/it/funzioni/collegamento-bancario'
    | '/it/funzioni/flusso-di-cassa'
    | '/it/funzioni/piano-zero-based'
    | '/it/funzioni/report'
    | '/it/guide/budget-zero-based'
    | '/it/guide/cancella-abbonamenti-inutili'
    | '/it/guide/previsione-flusso-di-cassa'
    | '/app/analyst'
    | '/app/docs'
    | '/app/forecast'
    | '/app/goals'
    | '/app/import'
    | '/app/plan'
    | '/app/planning'
    | '/app/reports'
    | '/app/settings'
    | '/app/transactions'
    | '/app/'
    | '/app/accounts/$accountId'
    | '/app/docs/$slug'
    | '/app/loans/$facilityId'
    | '/app/settings/accounts'
    | '/app/settings/bank-connections'
    | '/app/settings/credit'
    | '/app/settings/deleting'
    | '/app/settings/import'
    | '/app/subscriptions/create'
    | '/app/accounts/'
    | '/app/docs/'
    | '/app/settings/'
    | '/app/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/faq'
    | '/for-couples-and-families'
    | '/for-freelancers'
    | '/og'
    | '/open-source'
    | '/pricing'
    | '/vs-spreadsheets'
    | '/features/ai-analyst'
    | '/features/bank-connections'
    | '/features/cash-flow'
    | '/features/reports'
    | '/features/zero-based-plan'
    | '/guides/cancel-unused-subscriptions'
    | '/guides/cash-flow-forecast'
    | '/guides/zero-based-budgeting'
    | '/it/domande-frequenti'
    | '/it/open-source'
    | '/it/per-coppie-e-famiglie'
    | '/it/per-freelance-e-partita-iva'
    | '/it/prezzi'
    | '/it/vs-fogli-di-calcolo'
    | '/it'
    | '/it/funzioni/analyst-ai'
    | '/it/funzioni/collegamento-bancario'
    | '/it/funzioni/flusso-di-cassa'
    | '/it/funzioni/piano-zero-based'
    | '/it/funzioni/report'
    | '/it/guide/budget-zero-based'
    | '/it/guide/cancella-abbonamenti-inutili'
    | '/it/guide/previsione-flusso-di-cassa'
    | '/app/analyst'
    | '/app/forecast'
    | '/app/goals'
    | '/app/import'
    | '/app/plan'
    | '/app/planning'
    | '/app/reports'
    | '/app/transactions'
    | '/app'
    | '/app/accounts/$accountId'
    | '/app/docs/$slug'
    | '/app/loans/$facilityId'
    | '/app/settings/accounts'
    | '/app/settings/bank-connections'
    | '/app/settings/credit'
    | '/app/settings/deleting'
    | '/app/settings/import'
    | '/app/subscriptions/create'
    | '/app/accounts'
    | '/app/docs'
    | '/app/settings'
    | '/app/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/faq'
    | '/for-couples-and-families'
    | '/for-freelancers'
    | '/og'
    | '/open-source'
    | '/pricing'
    | '/vs-spreadsheets'
    | '/_authenticated/_app'
    | '/features/ai-analyst'
    | '/features/bank-connections'
    | '/features/cash-flow'
    | '/features/reports'
    | '/features/zero-based-plan'
    | '/guides/cancel-unused-subscriptions'
    | '/guides/cash-flow-forecast'
    | '/guides/zero-based-budgeting'
    | '/it/domande-frequenti'
    | '/it/open-source'
    | '/it/per-coppie-e-famiglie'
    | '/it/per-freelance-e-partita-iva'
    | '/it/prezzi'
    | '/it/vs-fogli-di-calcolo'
    | '/it/'
    | '/it/funzioni/analyst-ai'
    | '/it/funzioni/collegamento-bancario'
    | '/it/funzioni/flusso-di-cassa'
    | '/it/funzioni/piano-zero-based'
    | '/it/funzioni/report'
    | '/it/guide/budget-zero-based'
    | '/it/guide/cancella-abbonamenti-inutili'
    | '/it/guide/previsione-flusso-di-cassa'
    | '/_authenticated/_app/app/analyst'
    | '/_authenticated/_app/app/docs'
    | '/_authenticated/_app/app/forecast'
    | '/_authenticated/_app/app/goals'
    | '/_authenticated/_app/app/import'
    | '/_authenticated/_app/app/plan'
    | '/_authenticated/_app/app/planning'
    | '/_authenticated/_app/app/reports'
    | '/_authenticated/_app/app/settings'
    | '/_authenticated/_app/app/transactions'
    | '/_authenticated/_app/app/'
    | '/_authenticated/_app/app/accounts/$accountId'
    | '/_authenticated/_app/app/docs/$slug'
    | '/_authenticated/_app/app/loans/$facilityId'
    | '/_authenticated/_app/app/settings/accounts'
    | '/_authenticated/_app/app/settings/bank-connections'
    | '/_authenticated/_app/app/settings/credit'
    | '/_authenticated/_app/app/settings/deleting'
    | '/_authenticated/_app/app/settings/import'
    | '/_authenticated/_app/app/subscriptions/create'
    | '/_authenticated/_app/app/accounts/'
    | '/_authenticated/_app/app/docs/'
    | '/_authenticated/_app/app/settings/'
    | '/_authenticated/_app/app/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  FaqRoute: typeof FaqRoute
  ForCouplesAndFamiliesRoute: typeof ForCouplesAndFamiliesRoute
  ForFreelancersRoute: typeof ForFreelancersRoute
  OgRoute: typeof OgRoute
  OpenSourceRoute: typeof OpenSourceRoute
  PricingRoute: typeof PricingRoute
  VsSpreadsheetsRoute: typeof VsSpreadsheetsRoute
  FeaturesAiAnalystRoute: typeof FeaturesAiAnalystRoute
  FeaturesBankConnectionsRoute: typeof FeaturesBankConnectionsRoute
  FeaturesCashFlowRoute: typeof FeaturesCashFlowRoute
  FeaturesReportsRoute: typeof FeaturesReportsRoute
  FeaturesZeroBasedPlanRoute: typeof FeaturesZeroBasedPlanRoute
  GuidesCancelUnusedSubscriptionsRoute: typeof GuidesCancelUnusedSubscriptionsRoute
  GuidesCashFlowForecastRoute: typeof GuidesCashFlowForecastRoute
  GuidesZeroBasedBudgetingRoute: typeof GuidesZeroBasedBudgetingRoute
  ItDomandeFrequentiRoute: typeof ItDomandeFrequentiRoute
  ItOpenSourceRoute: typeof ItOpenSourceRoute
  ItPerCoppieEFamiglieRoute: typeof ItPerCoppieEFamiglieRoute
  ItPerFreelanceEPartitaIvaRoute: typeof ItPerFreelanceEPartitaIvaRoute
  ItPrezziRoute: typeof ItPrezziRoute
  ItVsFogliDiCalcoloRoute: typeof ItVsFogliDiCalcoloRoute
  ItIndexRoute: typeof ItIndexRoute
  ItFunzioniAnalystAiRoute: typeof ItFunzioniAnalystAiRoute
  ItFunzioniCollegamentoBancarioRoute: typeof ItFunzioniCollegamentoBancarioRoute
  ItFunzioniFlussoDiCassaRoute: typeof ItFunzioniFlussoDiCassaRoute
  ItFunzioniPianoZeroBasedRoute: typeof ItFunzioniPianoZeroBasedRoute
  ItFunzioniReportRoute: typeof ItFunzioniReportRoute
  ItGuideBudgetZeroBasedRoute: typeof ItGuideBudgetZeroBasedRoute
  ItGuideCancellaAbbonamentiInutiliRoute: typeof ItGuideCancellaAbbonamentiInutiliRoute
  ItGuidePrevisioneFlussoDiCassaRoute: typeof ItGuidePrevisioneFlussoDiCassaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-couples-and-families': {
      id: '/for-couples-and-families'
      path: '/for-couples-and-families'
      fullPath: '/for-couples-and-families'
      preLoaderRoute: typeof ForCouplesAndFamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-freelancers': {
      id: '/for-freelancers'
      path: '/for-freelancers'
      fullPath: '/for-freelancers'
      preLoaderRoute: typeof ForFreelancersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source': {
      id: '/open-source'
      path: '/open-source'
      fullPath: '/open-source'
      preLoaderRoute: typeof OpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs-spreadsheets': {
      id: '/vs-spreadsheets'
      path: '/vs-spreadsheets'
      fullPath: '/vs-spreadsheets'
      preLoaderRoute: typeof VsSpreadsheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/features/ai-analyst': {
      id: '/features/ai-analyst'
      path: '/features/ai-analyst'
      fullPath: '/features/ai-analyst'
      preLoaderRoute: typeof FeaturesAiAnalystRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/bank-connections': {
      id: '/features/bank-connections'
      path: '/features/bank-connections'
      fullPath: '/features/bank-connections'
      preLoaderRoute: typeof FeaturesBankConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/cash-flow': {
      id: '/features/cash-flow'
      path: '/features/cash-flow'
      fullPath: '/features/cash-flow'
      preLoaderRoute: typeof FeaturesCashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/reports': {
      id: '/features/reports'
      path: '/features/reports'
      fullPath: '/features/reports'
      preLoaderRoute: typeof FeaturesReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/zero-based-plan': {
      id: '/features/zero-based-plan'
      path: '/features/zero-based-plan'
      fullPath: '/features/zero-based-plan'
      preLoaderRoute: typeof FeaturesZeroBasedPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/cancel-unused-subscriptions': {
      id: '/guides/cancel-unused-subscriptions'
      path: '/guides/cancel-unused-subscriptions'
      fullPath: '/guides/cancel-unused-subscriptions'
      preLoaderRoute: typeof GuidesCancelUnusedSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/cash-flow-forecast': {
      id: '/guides/cash-flow-forecast'
      path: '/guides/cash-flow-forecast'
      fullPath: '/guides/cash-flow-forecast'
      preLoaderRoute: typeof GuidesCashFlowForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/zero-based-budgeting': {
      id: '/guides/zero-based-budgeting'
      path: '/guides/zero-based-budgeting'
      fullPath: '/guides/zero-based-budgeting'
      preLoaderRoute: typeof GuidesZeroBasedBudgetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/': {
      id: '/it/'
      path: '/it'
      fullPath: '/it/'
      preLoaderRoute: typeof ItIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/domande-frequenti': {
      id: '/it/domande-frequenti'
      path: '/it/domande-frequenti'
      fullPath: '/it/domande-frequenti'
      preLoaderRoute: typeof ItDomandeFrequentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/open-source': {
      id: '/it/open-source'
      path: '/it/open-source'
      fullPath: '/it/open-source'
      preLoaderRoute: typeof ItOpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/per-coppie-e-famiglie': {
      id: '/it/per-coppie-e-famiglie'
      path: '/it/per-coppie-e-famiglie'
      fullPath: '/it/per-coppie-e-famiglie'
      preLoaderRoute: typeof ItPerCoppieEFamiglieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/per-freelance-e-partita-iva': {
      id: '/it/per-freelance-e-partita-iva'
      path: '/it/per-freelance-e-partita-iva'
      fullPath: '/it/per-freelance-e-partita-iva'
      preLoaderRoute: typeof ItPerFreelanceEPartitaIvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/prezzi': {
      id: '/it/prezzi'
      path: '/it/prezzi'
      fullPath: '/it/prezzi'
      preLoaderRoute: typeof ItPrezziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/vs-fogli-di-calcolo': {
      id: '/it/vs-fogli-di-calcolo'
      path: '/it/vs-fogli-di-calcolo'
      fullPath: '/it/vs-fogli-di-calcolo'
      preLoaderRoute: typeof ItVsFogliDiCalcoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/funzioni/analyst-ai': {
      id: '/it/funzioni/analyst-ai'
      path: '/it/funzioni/analyst-ai'
      fullPath: '/it/funzioni/analyst-ai'
      preLoaderRoute: typeof ItFunzioniAnalystAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/funzioni/collegamento-bancario': {
      id: '/it/funzioni/collegamento-bancario'
      path: '/it/funzioni/collegamento-bancario'
      fullPath: '/it/funzioni/collegamento-bancario'
      preLoaderRoute: typeof ItFunzioniCollegamentoBancarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/funzioni/flusso-di-cassa': {
      id: '/it/funzioni/flusso-di-cassa'
      path: '/it/funzioni/flusso-di-cassa'
      fullPath: '/it/funzioni/flusso-di-cassa'
      preLoaderRoute: typeof ItFunzioniFlussoDiCassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/funzioni/piano-zero-based': {
      id: '/it/funzioni/piano-zero-based'
      path: '/it/funzioni/piano-zero-based'
      fullPath: '/it/funzioni/piano-zero-based'
      preLoaderRoute: typeof ItFunzioniPianoZeroBasedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/funzioni/report': {
      id: '/it/funzioni/report'
      path: '/it/funzioni/report'
      fullPath: '/it/funzioni/report'
      preLoaderRoute: typeof ItFunzioniReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/guide/budget-zero-based': {
      id: '/it/guide/budget-zero-based'
      path: '/it/guide/budget-zero-based'
      fullPath: '/it/guide/budget-zero-based'
      preLoaderRoute: typeof ItGuideBudgetZeroBasedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/guide/cancella-abbonamenti-inutili': {
      id: '/it/guide/cancella-abbonamenti-inutili'
      path: '/it/guide/cancella-abbonamenti-inutili'
      fullPath: '/it/guide/cancella-abbonamenti-inutili'
      preLoaderRoute: typeof ItGuideCancellaAbbonamentiInutiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it/guide/previsione-flusso-di-cassa': {
      id: '/it/guide/previsione-flusso-di-cassa'
      path: '/it/guide/previsione-flusso-di-cassa'
      fullPath: '/it/guide/previsione-flusso-di-cassa'
      preLoaderRoute: typeof ItGuidePrevisioneFlussoDiCassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/app/': {
      id: '/_authenticated/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/analyst': {
      id: '/_authenticated/_app/app/analyst'
      path: '/app/analyst'
      fullPath: '/app/analyst'
      preLoaderRoute: typeof AuthenticatedAppAppAnalystRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/docs': {
      id: '/_authenticated/_app/app/docs'
      path: '/app/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AuthenticatedAppAppDocsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/forecast': {
      id: '/_authenticated/_app/app/forecast'
      path: '/app/forecast'
      fullPath: '/app/forecast'
      preLoaderRoute: typeof AuthenticatedAppAppForecastRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/goals': {
      id: '/_authenticated/_app/app/goals'
      path: '/app/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AuthenticatedAppAppGoalsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/import': {
      id: '/_authenticated/_app/app/import'
      path: '/app/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AuthenticatedAppAppImportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/plan': {
      id: '/_authenticated/_app/app/plan'
      path: '/app/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AuthenticatedAppAppPlanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/planning': {
      id: '/_authenticated/_app/app/planning'
      path: '/app/planning'
      fullPath: '/app/planning'
      preLoaderRoute: typeof AuthenticatedAppAppPlanningRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/reports': {
      id: '/_authenticated/_app/app/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/settings': {
      id: '/_authenticated/_app/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/transactions': {
      id: '/_authenticated/_app/app/transactions'
      path: '/app/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AuthenticatedAppAppTransactionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/accounts/': {
      id: '/_authenticated/_app/app/accounts/'
      path: '/app/accounts'
      fullPath: '/app/accounts/'
      preLoaderRoute: typeof AuthenticatedAppAppAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/accounts/$accountId': {
      id: '/_authenticated/_app/app/accounts/$accountId'
      path: '/app/accounts/$accountId'
      fullPath: '/app/accounts/$accountId'
      preLoaderRoute: typeof AuthenticatedAppAppAccountsAccountIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/docs/': {
      id: '/_authenticated/_app/app/docs/'
      path: '/'
      fullPath: '/app/docs/'
      preLoaderRoute: typeof AuthenticatedAppAppDocsIndexRouteImport
      parentRoute: typeof AuthenticatedAppAppDocsRoute
    }
    '/_authenticated/_app/app/docs/$slug': {
      id: '/_authenticated/_app/app/docs/$slug'
      path: '/$slug'
      fullPath: '/app/docs/$slug'
      preLoaderRoute: typeof AuthenticatedAppAppDocsSlugRouteImport
      parentRoute: typeof AuthenticatedAppAppDocsRoute
    }
    '/_authenticated/_app/app/loans/$facilityId': {
      id: '/_authenticated/_app/app/loans/$facilityId'
      path: '/app/loans/$facilityId'
      fullPath: '/app/loans/$facilityId'
      preLoaderRoute: typeof AuthenticatedAppAppLoansFacilityIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/settings/': {
      id: '/_authenticated/_app/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppAppSettingsRoute
    }
    '/_authenticated/_app/app/settings/accounts': {
      id: '/_authenticated/_app/app/settings/accounts'
      path: '/accounts'
      fullPath: '/app/settings/accounts'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsAccountsRouteImport
      parentRoute: typeof AuthenticatedAppAppSettingsRoute
    }
    '/_authenticated/_app/app/settings/bank-connections': {
      id: '/_authenticated/_app/app/settings/bank-connections'
      path: '/bank-connections'
      fullPath: '/app/settings/bank-connections'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsBankConnectionsRouteImport
      parentRoute: typeof AuthenticatedAppAppSettingsRoute
    }
    '/_authenticated/_app/app/settings/credit': {
      id: '/_authenticated/_app/app/settings/credit'
      path: '/credit'
      fullPath: '/app/settings/credit'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsCreditRouteImport
      parentRoute: typeof AuthenticatedAppAppSettingsRoute
    }
    '/_authenticated/_app/app/settings/deleting': {
      id: '/_authenticated/_app/app/settings/deleting'
      path: '/deleting'
      fullPath: '/app/settings/deleting'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsDeletingRouteImport
      parentRoute: typeof AuthenticatedAppAppSettingsRoute
    }
    '/_authenticated/_app/app/settings/import': {
      id: '/_authenticated/_app/app/settings/import'
      path: '/import'
      fullPath: '/app/settings/import'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsImportRouteImport
      parentRoute: typeof AuthenticatedAppAppSettingsRoute
    }
    '/_authenticated/_app/app/subscriptions/': {
      id: '/_authenticated/_app/app/subscriptions/'
      path: '/app/subscriptions'
      fullPath: '/app/subscriptions/'
      preLoaderRoute: typeof AuthenticatedAppAppSubscriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/subscriptions/create': {
      id: '/_authenticated/_app/app/subscriptions/create'
      path: '/app/subscriptions/create'
      fullPath: '/app/subscriptions/create'
      preLoaderRoute: typeof AuthenticatedAppAppSubscriptionsCreateRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppAppDocsRouteChildren {
  AuthenticatedAppAppDocsSlugRoute: typeof AuthenticatedAppAppDocsSlugRoute
  AuthenticatedAppAppDocsIndexRoute: typeof AuthenticatedAppAppDocsIndexRoute
}

const AuthenticatedAppAppDocsRouteChildren: AuthenticatedAppAppDocsRouteChildren =
  {
    AuthenticatedAppAppDocsSlugRoute: AuthenticatedAppAppDocsSlugRoute,
    AuthenticatedAppAppDocsIndexRoute: AuthenticatedAppAppDocsIndexRoute,
  }

const AuthenticatedAppAppDocsRouteWithChildren =
  AuthenticatedAppAppDocsRoute._addFileChildren(
    AuthenticatedAppAppDocsRouteChildren,
  )

interface AuthenticatedAppAppSettingsRouteChildren {
  AuthenticatedAppAppSettingsAccountsRoute: typeof AuthenticatedAppAppSettingsAccountsRoute
  AuthenticatedAppAppSettingsBankConnectionsRoute: typeof AuthenticatedAppAppSettingsBankConnectionsRoute
  AuthenticatedAppAppSettingsCreditRoute: typeof AuthenticatedAppAppSettingsCreditRoute
  AuthenticatedAppAppSettingsDeletingRoute: typeof AuthenticatedAppAppSettingsDeletingRoute
  AuthenticatedAppAppSettingsImportRoute: typeof AuthenticatedAppAppSettingsImportRoute
  AuthenticatedAppAppSettingsIndexRoute: typeof AuthenticatedAppAppSettingsIndexRoute
}

const AuthenticatedAppAppSettingsRouteChildren: AuthenticatedAppAppSettingsRouteChildren =
  {
    AuthenticatedAppAppSettingsAccountsRoute:
      AuthenticatedAppAppSettingsAccountsRoute,
    AuthenticatedAppAppSettingsBankConnectionsRoute:
      AuthenticatedAppAppSettingsBankConnectionsRoute,
    AuthenticatedAppAppSettingsCreditRoute:
      AuthenticatedAppAppSettingsCreditRoute,
    AuthenticatedAppAppSettingsDeletingRoute:
      AuthenticatedAppAppSettingsDeletingRoute,
    AuthenticatedAppAppSettingsImportRoute:
      AuthenticatedAppAppSettingsImportRoute,
    AuthenticatedAppAppSettingsIndexRoute:
      AuthenticatedAppAppSettingsIndexRoute,
  }

const AuthenticatedAppAppSettingsRouteWithChildren =
  AuthenticatedAppAppSettingsRoute._addFileChildren(
    AuthenticatedAppAppSettingsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAppAnalystRoute: typeof AuthenticatedAppAppAnalystRoute
  AuthenticatedAppAppDocsRoute: typeof AuthenticatedAppAppDocsRouteWithChildren
  AuthenticatedAppAppForecastRoute: typeof AuthenticatedAppAppForecastRoute
  AuthenticatedAppAppGoalsRoute: typeof AuthenticatedAppAppGoalsRoute
  AuthenticatedAppAppImportRoute: typeof AuthenticatedAppAppImportRoute
  AuthenticatedAppAppPlanRoute: typeof AuthenticatedAppAppPlanRoute
  AuthenticatedAppAppPlanningRoute: typeof AuthenticatedAppAppPlanningRoute
  AuthenticatedAppAppReportsRoute: typeof AuthenticatedAppAppReportsRoute
  AuthenticatedAppAppSettingsRoute: typeof AuthenticatedAppAppSettingsRouteWithChildren
  AuthenticatedAppAppTransactionsRoute: typeof AuthenticatedAppAppTransactionsRoute
  AuthenticatedAppAppIndexRoute: typeof AuthenticatedAppAppIndexRoute
  AuthenticatedAppAppAccountsAccountIdRoute: typeof AuthenticatedAppAppAccountsAccountIdRoute
  AuthenticatedAppAppLoansFacilityIdRoute: typeof AuthenticatedAppAppLoansFacilityIdRoute
  AuthenticatedAppAppSubscriptionsCreateRoute: typeof AuthenticatedAppAppSubscriptionsCreateRoute
  AuthenticatedAppAppAccountsIndexRoute: typeof AuthenticatedAppAppAccountsIndexRoute
  AuthenticatedAppAppSubscriptionsIndexRoute: typeof AuthenticatedAppAppSubscriptionsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAppAnalystRoute: AuthenticatedAppAppAnalystRoute,
  AuthenticatedAppAppDocsRoute: AuthenticatedAppAppDocsRouteWithChildren,
  AuthenticatedAppAppForecastRoute: AuthenticatedAppAppForecastRoute,
  AuthenticatedAppAppGoalsRoute: AuthenticatedAppAppGoalsRoute,
  AuthenticatedAppAppImportRoute: AuthenticatedAppAppImportRoute,
  AuthenticatedAppAppPlanRoute: AuthenticatedAppAppPlanRoute,
  AuthenticatedAppAppPlanningRoute: AuthenticatedAppAppPlanningRoute,
  AuthenticatedAppAppReportsRoute: AuthenticatedAppAppReportsRoute,
  AuthenticatedAppAppSettingsRoute:
    AuthenticatedAppAppSettingsRouteWithChildren,
  AuthenticatedAppAppTransactionsRoute: AuthenticatedAppAppTransactionsRoute,
  AuthenticatedAppAppIndexRoute: AuthenticatedAppAppIndexRoute,
  AuthenticatedAppAppAccountsAccountIdRoute:
    AuthenticatedAppAppAccountsAccountIdRoute,
  AuthenticatedAppAppLoansFacilityIdRoute:
    AuthenticatedAppAppLoansFacilityIdRoute,
  AuthenticatedAppAppSubscriptionsCreateRoute:
    AuthenticatedAppAppSubscriptionsCreateRoute,
  AuthenticatedAppAppAccountsIndexRoute: AuthenticatedAppAppAccountsIndexRoute,
  AuthenticatedAppAppSubscriptionsIndexRoute:
    AuthenticatedAppAppSubscriptionsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  FaqRoute: FaqRoute,
  ForCouplesAndFamiliesRoute: ForCouplesAndFamiliesRoute,
  ForFreelancersRoute: ForFreelancersRoute,
  OgRoute: OgRoute,
  OpenSourceRoute: OpenSourceRoute,
  PricingRoute: PricingRoute,
  VsSpreadsheetsRoute: VsSpreadsheetsRoute,
  FeaturesAiAnalystRoute: FeaturesAiAnalystRoute,
  FeaturesBankConnectionsRoute: FeaturesBankConnectionsRoute,
  FeaturesCashFlowRoute: FeaturesCashFlowRoute,
  FeaturesReportsRoute: FeaturesReportsRoute,
  FeaturesZeroBasedPlanRoute: FeaturesZeroBasedPlanRoute,
  GuidesCancelUnusedSubscriptionsRoute: GuidesCancelUnusedSubscriptionsRoute,
  GuidesCashFlowForecastRoute: GuidesCashFlowForecastRoute,
  GuidesZeroBasedBudgetingRoute: GuidesZeroBasedBudgetingRoute,
  ItDomandeFrequentiRoute: ItDomandeFrequentiRoute,
  ItOpenSourceRoute: ItOpenSourceRoute,
  ItPerCoppieEFamiglieRoute: ItPerCoppieEFamiglieRoute,
  ItPerFreelanceEPartitaIvaRoute: ItPerFreelanceEPartitaIvaRoute,
  ItPrezziRoute: ItPrezziRoute,
  ItVsFogliDiCalcoloRoute: ItVsFogliDiCalcoloRoute,
  ItIndexRoute: ItIndexRoute,
  ItFunzioniAnalystAiRoute: ItFunzioniAnalystAiRoute,
  ItFunzioniCollegamentoBancarioRoute: ItFunzioniCollegamentoBancarioRoute,
  ItFunzioniFlussoDiCassaRoute: ItFunzioniFlussoDiCassaRoute,
  ItFunzioniPianoZeroBasedRoute: ItFunzioniPianoZeroBasedRoute,
  ItFunzioniReportRoute: ItFunzioniReportRoute,
  ItGuideBudgetZeroBasedRoute: ItGuideBudgetZeroBasedRoute,
  ItGuideCancellaAbbonamentiInutiliRoute:
    ItGuideCancellaAbbonamentiInutiliRoute,
  ItGuidePrevisioneFlussoDiCassaRoute: ItGuidePrevisioneFlussoDiCassaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
