/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppAppIndexRouteImport } from './routes/_authenticated/_app/app/index'
import { Route as AuthenticatedAppAppAnalystRouteImport } from './routes/_authenticated/_app/app/analyst'
import { Route as AuthenticatedAppAppDocsRouteImport } from './routes/_authenticated/_app/app/docs'
import { Route as AuthenticatedAppAppForecastRouteImport } from './routes/_authenticated/_app/app/forecast'
import { Route as AuthenticatedAppAppGoalsRouteImport } from './routes/_authenticated/_app/app/goals'
import { Route as AuthenticatedAppAppImportRouteImport } from './routes/_authenticated/_app/app/import'
import { Route as AuthenticatedAppAppPlanRouteImport } from './routes/_authenticated/_app/app/plan'
import { Route as AuthenticatedAppAppPlanningRouteImport } from './routes/_authenticated/_app/app/planning'
import { Route as AuthenticatedAppAppReportsRouteImport } from './routes/_authenticated/_app/app/reports'
import { Route as AuthenticatedAppAppSettingsRouteImport } from './routes/_authenticated/_app/app/settings'
import { Route as AuthenticatedAppAppTransactionsRouteImport } from './routes/_authenticated/_app/app/transactions'
import { Route as AuthenticatedAppAppAccountsIndexRouteImport } from './routes/_authenticated/_app/app/accounts/index'
import { Route as AuthenticatedAppAppAccountsAccountIdRouteImport } from './routes/_authenticated/_app/app/accounts/$accountId'
import { Route as AuthenticatedAppAppDocsIndexRouteImport } from './routes/_authenticated/_app/app/docs/index'
import { Route as AuthenticatedAppAppDocsSlugRouteImport } from './routes/_authenticated/_app/app/docs/$slug'
import { Route as AuthenticatedAppAppLoansFacilityIdRouteImport } from './routes/_authenticated/_app/app/loans/$facilityId'
import { Route as AuthenticatedAppAppSettingsIndexRouteImport } from './routes/_authenticated/_app/app/settings/index'
import { Route as AuthenticatedAppAppSettingsAccountsRouteImport } from './routes/_authenticated/_app/app/settings/accounts'
import { Route as AuthenticatedAppAppSettingsBankConnectionsRouteImport } from './routes/_authenticated/_app/app/settings/bank-connections'
import { Route as AuthenticatedAppAppSettingsCreditRouteImport } from './routes/_authenticated/_app/app/settings/credit'
import { Route as AuthenticatedAppAppSettingsImportRouteImport } from './routes/_authenticated/_app/app/settings/import'
import { Route as AuthenticatedAppAppSubscriptionsIndexRouteImport } from './routes/_authenticated/_app/app/subscriptions/index'
import { Route as AuthenticatedAppAppSubscriptionsCreateRouteImport } from './routes/_authenticated/_app/app/subscriptions/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppAppIndexRoute =
  AuthenticatedAppAppIndexRouteImport.update({
    id: '/app/',
    path: '/app/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppAnalystRoute =
  AuthenticatedAppAppAnalystRouteImport.update({
    id: '/app/analyst',
    path: '/app/analyst',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppDocsRoute = AuthenticatedAppAppDocsRouteImport.update({
  id: '/app/docs',
  path: '/app/docs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAppForecastRoute =
  AuthenticatedAppAppForecastRouteImport.update({
    id: '/app/forecast',
    path: '/app/forecast',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppGoalsRoute =
  AuthenticatedAppAppGoalsRouteImport.update({
    id: '/app/goals',
    path: '/app/goals',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppImportRoute =
  AuthenticatedAppAppImportRouteImport.update({
    id: '/app/import',
    path: '/app/import',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppPlanRoute = AuthenticatedAppAppPlanRouteImport.update({
  id: '/app/plan',
  path: '/app/plan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAppPlanningRoute =
  AuthenticatedAppAppPlanningRouteImport.update({
    id: '/app/planning',
    path: '/app/planning',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppReportsRoute =
  AuthenticatedAppAppReportsRouteImport.update({
    id: '/app/reports',
    path: '/app/reports',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppSettingsRoute =
  AuthenticatedAppAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppTransactionsRoute =
  AuthenticatedAppAppTransactionsRouteImport.update({
    id: '/app/transactions',
    path: '/app/transactions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppAccountsIndexRoute =
  AuthenticatedAppAppAccountsIndexRouteImport.update({
    id: '/app/accounts/',
    path: '/app/accounts/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppAccountsAccountIdRoute =
  AuthenticatedAppAppAccountsAccountIdRouteImport.update({
    id: '/app/accounts/$accountId',
    path: '/app/accounts/$accountId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppDocsIndexRoute =
  AuthenticatedAppAppDocsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAppDocsRoute,
  } as any)
const AuthenticatedAppAppDocsSlugRoute =
  AuthenticatedAppAppDocsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAppAppDocsRoute,
  } as any)
const AuthenticatedAppAppLoansFacilityIdRoute =
  AuthenticatedAppAppLoansFacilityIdRouteImport.update({
    id: '/app/loans/$facilityId',
    path: '/app/loans/$facilityId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppSettingsIndexRoute =
  AuthenticatedAppAppSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAppSettingsRoute,
  } as any)
const AuthenticatedAppAppSettingsAccountsRoute =
  AuthenticatedAppAppSettingsAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAppAppSettingsRoute,
  } as any)
const AuthenticatedAppAppSettingsBankConnectionsRoute =
  AuthenticatedAppAppSettingsBankConnectionsRouteImport.update({
    id: '/bank-connections',
    path: '/bank-connections',
    getParentRoute: () => AuthenticatedAppAppSettingsRoute,
  } as any)
const AuthenticatedAppAppSettingsCreditRoute =
  AuthenticatedAppAppSettingsCreditRouteImport.update({
    id: '/credit',
    path: '/credit',
    getParentRoute: () => AuthenticatedAppAppSettingsRoute,
  } as any)
const AuthenticatedAppAppSettingsImportRoute =
  AuthenticatedAppAppSettingsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAppAppSettingsRoute,
  } as any)
const AuthenticatedAppAppSubscriptionsIndexRoute =
  AuthenticatedAppAppSubscriptionsIndexRouteImport.update({
    id: '/app/subscriptions/',
    path: '/app/subscriptions/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAppSubscriptionsCreateRoute =
  AuthenticatedAppAppSubscriptionsCreateRouteImport.update({
    id: '/app/subscriptions/create',
    path: '/app/subscriptions/create',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/app/analyst': typeof AuthenticatedAppAppAnalystRoute
  '/app/docs': typeof AuthenticatedAppAppDocsRouteWithChildren
  '/app/forecast': typeof AuthenticatedAppAppForecastRoute
  '/app/goals': typeof AuthenticatedAppAppGoalsRoute
  '/app/import': typeof AuthenticatedAppAppImportRoute
  '/app/plan': typeof AuthenticatedAppAppPlanRoute
  '/app/planning': typeof AuthenticatedAppAppPlanningRoute
  '/app/reports': typeof AuthenticatedAppAppReportsRoute
  '/app/settings': typeof AuthenticatedAppAppSettingsRouteWithChildren
  '/app/transactions': typeof AuthenticatedAppAppTransactionsRoute
  '/app/': typeof AuthenticatedAppAppIndexRoute
  '/app/accounts/$accountId': typeof AuthenticatedAppAppAccountsAccountIdRoute
  '/app/docs/$slug': typeof AuthenticatedAppAppDocsSlugRoute
  '/app/loans/$facilityId': typeof AuthenticatedAppAppLoansFacilityIdRoute
  '/app/settings/accounts': typeof AuthenticatedAppAppSettingsAccountsRoute
  '/app/settings/bank-connections': typeof AuthenticatedAppAppSettingsBankConnectionsRoute
  '/app/settings/credit': typeof AuthenticatedAppAppSettingsCreditRoute
  '/app/settings/import': typeof AuthenticatedAppAppSettingsImportRoute
  '/app/subscriptions/create': typeof AuthenticatedAppAppSubscriptionsCreateRoute
  '/app/accounts/': typeof AuthenticatedAppAppAccountsIndexRoute
  '/app/docs/': typeof AuthenticatedAppAppDocsIndexRoute
  '/app/settings/': typeof AuthenticatedAppAppSettingsIndexRoute
  '/app/subscriptions/': typeof AuthenticatedAppAppSubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/app/analyst': typeof AuthenticatedAppAppAnalystRoute
  '/app/forecast': typeof AuthenticatedAppAppForecastRoute
  '/app/goals': typeof AuthenticatedAppAppGoalsRoute
  '/app/import': typeof AuthenticatedAppAppImportRoute
  '/app/plan': typeof AuthenticatedAppAppPlanRoute
  '/app/planning': typeof AuthenticatedAppAppPlanningRoute
  '/app/reports': typeof AuthenticatedAppAppReportsRoute
  '/app/transactions': typeof AuthenticatedAppAppTransactionsRoute
  '/app': typeof AuthenticatedAppAppIndexRoute
  '/app/accounts/$accountId': typeof AuthenticatedAppAppAccountsAccountIdRoute
  '/app/docs/$slug': typeof AuthenticatedAppAppDocsSlugRoute
  '/app/loans/$facilityId': typeof AuthenticatedAppAppLoansFacilityIdRoute
  '/app/settings/accounts': typeof AuthenticatedAppAppSettingsAccountsRoute
  '/app/settings/bank-connections': typeof AuthenticatedAppAppSettingsBankConnectionsRoute
  '/app/settings/credit': typeof AuthenticatedAppAppSettingsCreditRoute
  '/app/settings/import': typeof AuthenticatedAppAppSettingsImportRoute
  '/app/subscriptions/create': typeof AuthenticatedAppAppSubscriptionsCreateRoute
  '/app/accounts': typeof AuthenticatedAppAppAccountsIndexRoute
  '/app/docs': typeof AuthenticatedAppAppDocsIndexRoute
  '/app/settings': typeof AuthenticatedAppAppSettingsIndexRoute
  '/app/subscriptions': typeof AuthenticatedAppAppSubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/_app/app/analyst': typeof AuthenticatedAppAppAnalystRoute
  '/_authenticated/_app/app/docs': typeof AuthenticatedAppAppDocsRouteWithChildren
  '/_authenticated/_app/app/forecast': typeof AuthenticatedAppAppForecastRoute
  '/_authenticated/_app/app/goals': typeof AuthenticatedAppAppGoalsRoute
  '/_authenticated/_app/app/import': typeof AuthenticatedAppAppImportRoute
  '/_authenticated/_app/app/plan': typeof AuthenticatedAppAppPlanRoute
  '/_authenticated/_app/app/planning': typeof AuthenticatedAppAppPlanningRoute
  '/_authenticated/_app/app/reports': typeof AuthenticatedAppAppReportsRoute
  '/_authenticated/_app/app/settings': typeof AuthenticatedAppAppSettingsRouteWithChildren
  '/_authenticated/_app/app/transactions': typeof AuthenticatedAppAppTransactionsRoute
  '/_authenticated/_app/app/': typeof AuthenticatedAppAppIndexRoute
  '/_authenticated/_app/app/accounts/$accountId': typeof AuthenticatedAppAppAccountsAccountIdRoute
  '/_authenticated/_app/app/docs/$slug': typeof AuthenticatedAppAppDocsSlugRoute
  '/_authenticated/_app/app/loans/$facilityId': typeof AuthenticatedAppAppLoansFacilityIdRoute
  '/_authenticated/_app/app/settings/accounts': typeof AuthenticatedAppAppSettingsAccountsRoute
  '/_authenticated/_app/app/settings/bank-connections': typeof AuthenticatedAppAppSettingsBankConnectionsRoute
  '/_authenticated/_app/app/settings/credit': typeof AuthenticatedAppAppSettingsCreditRoute
  '/_authenticated/_app/app/settings/import': typeof AuthenticatedAppAppSettingsImportRoute
  '/_authenticated/_app/app/subscriptions/create': typeof AuthenticatedAppAppSubscriptionsCreateRoute
  '/_authenticated/_app/app/accounts/': typeof AuthenticatedAppAppAccountsIndexRoute
  '/_authenticated/_app/app/docs/': typeof AuthenticatedAppAppDocsIndexRoute
  '/_authenticated/_app/app/settings/': typeof AuthenticatedAppAppSettingsIndexRoute
  '/_authenticated/_app/app/subscriptions/': typeof AuthenticatedAppAppSubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/app/analyst'
    | '/app/docs'
    | '/app/forecast'
    | '/app/goals'
    | '/app/import'
    | '/app/plan'
    | '/app/planning'
    | '/app/reports'
    | '/app/settings'
    | '/app/transactions'
    | '/app/'
    | '/app/accounts/$accountId'
    | '/app/docs/$slug'
    | '/app/loans/$facilityId'
    | '/app/settings/accounts'
    | '/app/settings/bank-connections'
    | '/app/settings/credit'
    | '/app/settings/import'
    | '/app/subscriptions/create'
    | '/app/accounts/'
    | '/app/docs/'
    | '/app/settings/'
    | '/app/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/app/analyst'
    | '/app/forecast'
    | '/app/goals'
    | '/app/import'
    | '/app/plan'
    | '/app/planning'
    | '/app/reports'
    | '/app/transactions'
    | '/app'
    | '/app/accounts/$accountId'
    | '/app/docs/$slug'
    | '/app/loans/$facilityId'
    | '/app/settings/accounts'
    | '/app/settings/bank-connections'
    | '/app/settings/credit'
    | '/app/settings/import'
    | '/app/subscriptions/create'
    | '/app/accounts'
    | '/app/docs'
    | '/app/settings'
    | '/app/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/_app'
    | '/_authenticated/_app/app/analyst'
    | '/_authenticated/_app/app/docs'
    | '/_authenticated/_app/app/forecast'
    | '/_authenticated/_app/app/goals'
    | '/_authenticated/_app/app/import'
    | '/_authenticated/_app/app/plan'
    | '/_authenticated/_app/app/planning'
    | '/_authenticated/_app/app/reports'
    | '/_authenticated/_app/app/settings'
    | '/_authenticated/_app/app/transactions'
    | '/_authenticated/_app/app/'
    | '/_authenticated/_app/app/accounts/$accountId'
    | '/_authenticated/_app/app/docs/$slug'
    | '/_authenticated/_app/app/loans/$facilityId'
    | '/_authenticated/_app/app/settings/accounts'
    | '/_authenticated/_app/app/settings/bank-connections'
    | '/_authenticated/_app/app/settings/credit'
    | '/_authenticated/_app/app/settings/import'
    | '/_authenticated/_app/app/subscriptions/create'
    | '/_authenticated/_app/app/accounts/'
    | '/_authenticated/_app/app/docs/'
    | '/_authenticated/_app/app/settings/'
    | '/_authenticated/_app/app/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/app/': {
      id: '/_authenticated/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/analyst': {
      id: '/_authenticated/_app/app/analyst'
      path: '/app/analyst'
      fullPath: '/app/analyst'
      preLoaderRoute: typeof AuthenticatedAppAppAnalystRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/docs': {
      id: '/_authenticated/_app/app/docs'
      path: '/app/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AuthenticatedAppAppDocsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/forecast': {
      id: '/_authenticated/_app/app/forecast'
      path: '/app/forecast'
      fullPath: '/app/forecast'
      preLoaderRoute: typeof AuthenticatedAppAppForecastRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/goals': {
      id: '/_authenticated/_app/app/goals'
      path: '/app/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AuthenticatedAppAppGoalsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/import': {
      id: '/_authenticated/_app/app/import'
      path: '/app/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AuthenticatedAppAppImportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/plan': {
      id: '/_authenticated/_app/app/plan'
      path: '/app/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AuthenticatedAppAppPlanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/planning': {
      id: '/_authenticated/_app/app/planning'
      path: '/app/planning'
      fullPath: '/app/planning'
      preLoaderRoute: typeof AuthenticatedAppAppPlanningRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/reports': {
      id: '/_authenticated/_app/app/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/settings': {
      id: '/_authenticated/_app/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/transactions': {
      id: '/_authenticated/_app/app/transactions'
      path: '/app/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AuthenticatedAppAppTransactionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/accounts/': {
      id: '/_authenticated/_app/app/accounts/'
      path: '/app/accounts'
      fullPath: '/app/accounts/'
      preLoaderRoute: typeof AuthenticatedAppAppAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/accounts/$accountId': {
      id: '/_authenticated/_app/app/accounts/$accountId'
      path: '/app/accounts/$accountId'
      fullPath: '/app/accounts/$accountId'
      preLoaderRoute: typeof AuthenticatedAppAppAccountsAccountIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/docs/': {
      id: '/_authenticated/_app/app/docs/'
      path: '/'
      fullPath: '/app/docs/'
      preLoaderRoute: typeof AuthenticatedAppAppDocsIndexRouteImport
      parentRoute: typeof AuthenticatedAppAppDocsRoute
    }
    '/_authenticated/_app/app/docs/$slug': {
      id: '/_authenticated/_app/app/docs/$slug'
      path: '/$slug'
      fullPath: '/app/docs/$slug'
      preLoaderRoute: typeof AuthenticatedAppAppDocsSlugRouteImport
      parentRoute: typeof AuthenticatedAppAppDocsRoute
    }
    '/_authenticated/_app/app/loans/$facilityId': {
      id: '/_authenticated/_app/app/loans/$facilityId'
      path: '/app/loans/$facilityId'
      fullPath: '/app/loans/$facilityId'
      preLoaderRoute: typeof AuthenticatedAppAppLoansFacilityIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/settings/': {
      id: '/_authenticated/_app/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppAppSettingsRoute
    }
    '/_authenticated/_app/app/settings/accounts': {
      id: '/_authenticated/_app/app/settings/accounts'
      path: '/accounts'
      fullPath: '/app/settings/accounts'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsAccountsRouteImport
      parentRoute: typeof AuthenticatedAppAppSettingsRoute
    }
    '/_authenticated/_app/app/settings/bank-connections': {
      id: '/_authenticated/_app/app/settings/bank-connections'
      path: '/bank-connections'
      fullPath: '/app/settings/bank-connections'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsBankConnectionsRouteImport
      parentRoute: typeof AuthenticatedAppAppSettingsRoute
    }
    '/_authenticated/_app/app/settings/credit': {
      id: '/_authenticated/_app/app/settings/credit'
      path: '/credit'
      fullPath: '/app/settings/credit'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsCreditRouteImport
      parentRoute: typeof AuthenticatedAppAppSettingsRoute
    }
    '/_authenticated/_app/app/settings/import': {
      id: '/_authenticated/_app/app/settings/import'
      path: '/import'
      fullPath: '/app/settings/import'
      preLoaderRoute: typeof AuthenticatedAppAppSettingsImportRouteImport
      parentRoute: typeof AuthenticatedAppAppSettingsRoute
    }
    '/_authenticated/_app/app/subscriptions/': {
      id: '/_authenticated/_app/app/subscriptions/'
      path: '/app/subscriptions'
      fullPath: '/app/subscriptions/'
      preLoaderRoute: typeof AuthenticatedAppAppSubscriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/app/subscriptions/create': {
      id: '/_authenticated/_app/app/subscriptions/create'
      path: '/app/subscriptions/create'
      fullPath: '/app/subscriptions/create'
      preLoaderRoute: typeof AuthenticatedAppAppSubscriptionsCreateRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppAppDocsRouteChildren {
  AuthenticatedAppAppDocsSlugRoute: typeof AuthenticatedAppAppDocsSlugRoute
  AuthenticatedAppAppDocsIndexRoute: typeof AuthenticatedAppAppDocsIndexRoute
}

const AuthenticatedAppAppDocsRouteChildren: AuthenticatedAppAppDocsRouteChildren =
  {
    AuthenticatedAppAppDocsSlugRoute: AuthenticatedAppAppDocsSlugRoute,
    AuthenticatedAppAppDocsIndexRoute: AuthenticatedAppAppDocsIndexRoute,
  }

const AuthenticatedAppAppDocsRouteWithChildren =
  AuthenticatedAppAppDocsRoute._addFileChildren(
    AuthenticatedAppAppDocsRouteChildren,
  )

interface AuthenticatedAppAppSettingsRouteChildren {
  AuthenticatedAppAppSettingsAccountsRoute: typeof AuthenticatedAppAppSettingsAccountsRoute
  AuthenticatedAppAppSettingsBankConnectionsRoute: typeof AuthenticatedAppAppSettingsBankConnectionsRoute
  AuthenticatedAppAppSettingsCreditRoute: typeof AuthenticatedAppAppSettingsCreditRoute
  AuthenticatedAppAppSettingsImportRoute: typeof AuthenticatedAppAppSettingsImportRoute
  AuthenticatedAppAppSettingsIndexRoute: typeof AuthenticatedAppAppSettingsIndexRoute
}

const AuthenticatedAppAppSettingsRouteChildren: AuthenticatedAppAppSettingsRouteChildren =
  {
    AuthenticatedAppAppSettingsAccountsRoute:
      AuthenticatedAppAppSettingsAccountsRoute,
    AuthenticatedAppAppSettingsBankConnectionsRoute:
      AuthenticatedAppAppSettingsBankConnectionsRoute,
    AuthenticatedAppAppSettingsCreditRoute:
      AuthenticatedAppAppSettingsCreditRoute,
    AuthenticatedAppAppSettingsImportRoute:
      AuthenticatedAppAppSettingsImportRoute,
    AuthenticatedAppAppSettingsIndexRoute:
      AuthenticatedAppAppSettingsIndexRoute,
  }

const AuthenticatedAppAppSettingsRouteWithChildren =
  AuthenticatedAppAppSettingsRoute._addFileChildren(
    AuthenticatedAppAppSettingsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAppAnalystRoute: typeof AuthenticatedAppAppAnalystRoute
  AuthenticatedAppAppDocsRoute: typeof AuthenticatedAppAppDocsRouteWithChildren
  AuthenticatedAppAppForecastRoute: typeof AuthenticatedAppAppForecastRoute
  AuthenticatedAppAppGoalsRoute: typeof AuthenticatedAppAppGoalsRoute
  AuthenticatedAppAppImportRoute: typeof AuthenticatedAppAppImportRoute
  AuthenticatedAppAppPlanRoute: typeof AuthenticatedAppAppPlanRoute
  AuthenticatedAppAppPlanningRoute: typeof AuthenticatedAppAppPlanningRoute
  AuthenticatedAppAppReportsRoute: typeof AuthenticatedAppAppReportsRoute
  AuthenticatedAppAppSettingsRoute: typeof AuthenticatedAppAppSettingsRouteWithChildren
  AuthenticatedAppAppTransactionsRoute: typeof AuthenticatedAppAppTransactionsRoute
  AuthenticatedAppAppIndexRoute: typeof AuthenticatedAppAppIndexRoute
  AuthenticatedAppAppAccountsAccountIdRoute: typeof AuthenticatedAppAppAccountsAccountIdRoute
  AuthenticatedAppAppLoansFacilityIdRoute: typeof AuthenticatedAppAppLoansFacilityIdRoute
  AuthenticatedAppAppSubscriptionsCreateRoute: typeof AuthenticatedAppAppSubscriptionsCreateRoute
  AuthenticatedAppAppAccountsIndexRoute: typeof AuthenticatedAppAppAccountsIndexRoute
  AuthenticatedAppAppSubscriptionsIndexRoute: typeof AuthenticatedAppAppSubscriptionsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAppAnalystRoute: AuthenticatedAppAppAnalystRoute,
  AuthenticatedAppAppDocsRoute: AuthenticatedAppAppDocsRouteWithChildren,
  AuthenticatedAppAppForecastRoute: AuthenticatedAppAppForecastRoute,
  AuthenticatedAppAppGoalsRoute: AuthenticatedAppAppGoalsRoute,
  AuthenticatedAppAppImportRoute: AuthenticatedAppAppImportRoute,
  AuthenticatedAppAppPlanRoute: AuthenticatedAppAppPlanRoute,
  AuthenticatedAppAppPlanningRoute: AuthenticatedAppAppPlanningRoute,
  AuthenticatedAppAppReportsRoute: AuthenticatedAppAppReportsRoute,
  AuthenticatedAppAppSettingsRoute:
    AuthenticatedAppAppSettingsRouteWithChildren,
  AuthenticatedAppAppTransactionsRoute: AuthenticatedAppAppTransactionsRoute,
  AuthenticatedAppAppIndexRoute: AuthenticatedAppAppIndexRoute,
  AuthenticatedAppAppAccountsAccountIdRoute:
    AuthenticatedAppAppAccountsAccountIdRoute,
  AuthenticatedAppAppLoansFacilityIdRoute:
    AuthenticatedAppAppLoansFacilityIdRoute,
  AuthenticatedAppAppSubscriptionsCreateRoute:
    AuthenticatedAppAppSubscriptionsCreateRoute,
  AuthenticatedAppAppAccountsIndexRoute: AuthenticatedAppAppAccountsIndexRoute,
  AuthenticatedAppAppSubscriptionsIndexRoute:
    AuthenticatedAppAppSubscriptionsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
